// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HbmToConform
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class MapTemplate : MapTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System.ComponentModel;\r\nusing NHibernate.Mapping.ByCode;\r\nusing NHibernate." +
                    "Mapping.ByCode.Conformist;\r\n\r\nnamespace ");
            
            #line 10 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.FullType.Replace("." + Model.DomainClassName, "")));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    [Localizable(false)]\r\n    public class ");
            
            #line 13 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DomainClassName));
            
            #line default
            #line hidden
            this.Write("Map : ClassMapping<");
            
            #line 13 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.FullType));
            
            #line default
            #line hidden
            this.Write("> \r\n    {\r\n        public ");
            
            #line 15 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DomainClassName));
            
            #line default
            #line hidden
            this.Write("Map()\r\n        {\r\n            Table(\"");
            
            #line 17 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ClassTable));
            
            #line default
            #line hidden
            this.Write("\");\r\n            Lazy(");
            
            #line 18 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Lazy.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write("); \r\n            Id(x => x.");
            
            #line 19 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Id.Name));
            
            #line default
            #line hidden
            this.Write(", idMap =>\r\n            {\r\n                idMap.Generator(");
            
            #line 21 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Id.Generator));
            
            #line default
            #line hidden
            this.Write(");\r\n                idMap.Column(\"");
            
            #line 22 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Id.ColumnName));
            
            #line default
            #line hidden
            this.Write("\");\r\n                ");
            
            #line 23 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (Model.Id.UnsavedValue != null) {
            
            #line default
            #line hidden
            this.Write("                idMap.UnsavedValue(");
            
            #line 24 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Id.UnsavedValue));
            
            #line default
            #line hidden
            this.Write(");\r\n                ");
            
            #line 25 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            });\r\n\r\n            ");
            
            #line 28 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 foreach (var ptp in Model.Properties) {
            
            #line default
            #line hidden
            this.Write("            Property(x => x.");
            
            #line 29 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ptp.Name));
            
            #line default
            #line hidden
            this.Write(", clm => { \r\n                ");
            
            #line 30 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (ptp.ColumnName != null) { 
            
            #line default
            #line hidden
            this.Write("                clm.Column(\"");
            
            #line 31 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ptp.ColumnName));
            
            #line default
            #line hidden
            this.Write("\");\r\n                ");
            
            #line 32 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 33 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (ptp.NotNull) {
            
            #line default
            #line hidden
            this.Write("                clm.NotNullable(true);\r\n                ");
            
            #line 35 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 36 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (ptp.Unique) {
            
            #line default
            #line hidden
            this.Write("                clm.Unique(true);\r\n                ");
            
            #line 38 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 39 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if(ptp.NoUpdate) {
            
            #line default
            #line hidden
            this.Write("                clm.Update(false);\r\n                ");
            
            #line 41 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 42 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if(ptp.NoInsert) {
            
            #line default
            #line hidden
            this.Write("                clm.Insert(false);\r\n                ");
            
            #line 44 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 45 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if(ptp.Length != null) {
            
            #line default
            #line hidden
            this.Write("                clm.Length(");
            
            #line 46 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ptp.Length));
            
            #line default
            #line hidden
            this.Write(");\r\n                ");
            
            #line 47 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("            });\r\n            ");
            
            #line 49 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 50 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 foreach (var mto in Model.ManyToOnes) {
            
            #line default
            #line hidden
            this.Write("            ManyToOne(x => x.");
            
            #line 51 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mto.Name));
            
            #line default
            #line hidden
            this.Write(", mto => { \r\n                mto.Column(\"");
            
            #line 52 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mto.ColumnName));
            
            #line default
            #line hidden
            this.Write("\"); \r\n                ");
            
            #line 53 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if(mto.NotFoundMode != null) {
            
            #line default
            #line hidden
            this.Write("                mto.NotFound(");
            
            #line 54 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mto.NotFoundMode));
            
            #line default
            #line hidden
            this.Write(");\r\n                ");
            
            #line 55 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 56 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if(mto.NoUpdate) {
            
            #line default
            #line hidden
            this.Write("                mto.Update(false);\r\n                ");
            
            #line 58 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 59 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if(mto.NoInsert) {
            
            #line default
            #line hidden
            this.Write("                mto.Insert(false);\r\n                ");
            
            #line 61 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 62 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (mto.Lazy != null) {
            
            #line default
            #line hidden
            this.Write("                mto.Lazy(");
            
            #line 63 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mto.Lazy));
            
            #line default
            #line hidden
            this.Write(");\r\n                ");
            
            #line 64 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 65 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (mto.NotNull) {
            
            #line default
            #line hidden
            this.Write("                mto.NotNullable(true);\r\n                ");
            
            #line 67 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 68 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (mto.Cascade != null) {
            
            #line default
            #line hidden
            this.Write("                mto.Cascade(");
            
            #line 69 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mto.Cascade));
            
            #line default
            #line hidden
            this.Write(");\r\n                ");
            
            #line 70 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("            });\r\n\r\n            ");
            
            #line 73 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 74 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 foreach (var bag in Model.Bags) {
            
            #line default
            #line hidden
            this.Write("            Bag(x => x.");
            
            #line 75 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag.Name));
            
            #line default
            #line hidden
            this.Write(", bag => { \r\n                bag.Table(\"");
            
            #line 76 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag.Table));
            
            #line default
            #line hidden
            this.Write("\"); \r\n                ");
            
            #line 77 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (bag.Lazy) {
            
            #line default
            #line hidden
            this.Write("                bag.Lazy(CollectionLazy.Lazy);\r\n                ");
            
            #line 79 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write("                bag.Lazy(CollectionLazy.NoLazy);\r\n                ");
            
            #line 81 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 82 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (bag.Inverse) {
            
            #line default
            #line hidden
            this.Write("                bag.Inverse(true);\r\n                ");
            
            #line 84 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 85 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (bag.Cascade != null) {
            
            #line default
            #line hidden
            this.Write("                bag.Cascade(");
            
            #line 86 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag.Cascade));
            
            #line default
            #line hidden
            this.Write(");\r\n                ");
            
            #line 87 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 88 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if(bag.KeyColumn != null) {
            
            #line default
            #line hidden
            this.Write("                bag.Key(k => k.Column(\"");
            
            #line 89 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag.KeyColumn));
            
            #line default
            #line hidden
            this.Write("\"));\r\n                ");
            
            #line 90 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 91 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if(bag.OrderBy != null) {
            
            #line default
            #line hidden
            this.Write("                bag.OrderBy(\"");
            
            #line 92 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag.OrderBy));
            
            #line default
            #line hidden
            this.Write("\");\r\n                ");
            
            #line 93 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("            }, rel => {\r\n                    rel.");
            
            #line 95 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag.RelType));
            
            #line default
            #line hidden
            this.Write("();\r\n                    ");
            
            #line 96 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 if (bag.RelColumn != null) {
            
            #line default
            #line hidden
            this.Write("                    rel.Column(\"");
            
            #line 97 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag.RelColumn));
            
            #line default
            #line hidden
            this.Write("\");\r\n                    ");
            
            #line 98 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("            });\r\n        ");
            
            #line 100 "C:\projects\HbmToConform\HbmToConform\MapTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class MapTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
